### ISSUE TITLE
Feature Request: Duplicate Line or Selection for Carets

### ISSUE THREAD

**Issue by j-a-s-o-n-g** [MohammadMD1383/Actionable#19]
https://github.com/vsch/MissingInActions/tree/4f2f9c1264144ed9e2db082614c57cb48eb8328b#:~:text=Duplicate%20Line%20or%20Selection%20for%20Carets

https://github.com/vsch/MissingInActions/raw/master/assets/images/noload/MiaDupeForClipboardCarets.gif

The source code for MIA is super complex, with a dialog box for options. Since this (I imagine) would be a huge undertaking, a simplified action would literally just duplicate the lines for x lines in clipboard and paste/retain caret position.

https://github.com/vsch/MissingInActions/blob/4f2f9c1264144ed9e2db082614c57cb48eb8328b/src/com/vladsch/MissingInActions/actions/line/DuplicateForClipboardCaretsActionHandler.java

**Comment by MohammadMD1383** [comment]
Fantastic action!

**Comment by MohammadMD1383** [comment]
Hi, you can check this nightly build and give feedback.

I have plans to add such action for selection too so this is not closed yet

**Comment by j-a-s-o-n-g** [comment]
So far so good! I tested without a selection and it works as expected!

**Comment by j-a-s-o-n-g** [comment]
I used this feature (after updating to the one that overwrites selection) and the first time I got this error:

`java.lang.UnsupportedOperationException
  at java.base/java.util.AbstractList.remove(AbstractList.java:167)
  at kotlin.collections.CollectionsKt__MutableCollectionsKt.removeFirst(MutableCollections.kt:246)
  at ir.mmd.intellijDev.Actionable.text.DuplicateLineAndPasteClipboardContentAction$perform$1.invoke(DuplicateLineAndPasteClipboardContentAction.kt:36)
  at ir.mmd.intellijDev.Actionable.text.DuplicateLineAndPasteClipboardContentAction$perform$1.invoke(DuplicateLineAndPasteClipboardContentAction.kt:35)
  at ir.mmd.intellijDev.Actionable.util.ext.ProjectKt$sam$i$java_lang_Runnable$0.run(Project.kt)
  at com.intellij.openapi.command.WriteCommandAction.lambda$runWriteCommandAction$4(WriteCommandAction.java:362)
  at com.intellij.openapi.command.WriteCommandAction$BuilderImpl.lambda$doRunWriteCommandAction$1(WriteCommandAction.java:150)
  at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:980)
  at com.intellij.openapi.command.WriteCommandAction$BuilderImpl.lambda$doRunWriteCommandAction$2(WriteCommandAction.java:148)
  at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:219)
  at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:184)
  at com.intellij.openapi.command.WriteCommandAction$BuilderImpl.doRunWriteCommandAction(WriteCommandAction.java:157)
  at com.intellij.openapi.command.WriteCommandAction$BuilderImpl.run(WriteCommandAction.java:124)
  at com.intellij.openapi.command.WriteCommandAction.runWriteCommandAction(WriteCommandAction.java:362)
  at com.intellij.openapi.command.WriteCommandAction.runWriteCommandAction(WriteCommandAction.java:350)
  at ir.mmd.intellijDev.Actionable.text.DuplicateLineAndPasteClipboardContentAction.perform(DuplicateLineAndPasteClipboardContentAction.kt:68)
  at ir.mmd.intellijDev.Actionable.action.SingleCaretAction.actionPerformed(Base.kt:98)
  at com.intellij.openapi.actionSystem.ex.ActionUtil.doPerformActionOrShowPopup(ActionUtil.java:327)
  at com.intellij.openapi.keymap.impl.ActionProcessor.performAction(ActionProcessor.java:47)
  at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:584)
  at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$doPerformActionInner$9(IdeKeyEventDispatcher.java:706)
  at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
  at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:94)
  at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$doPerformActionInner$10(IdeKeyEventDispatcher.java:706)
  at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:350)
  at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.doPerformActionInner(IdeKeyEventDispatcher.java:703)
  at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:647)
  at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:595)
  at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:478)
  at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:467)
  at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:225)
  at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.java:815)
  at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:750)
  at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$5(IdeEventQueue.java:437)
  at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
  at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:436)
  at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
  at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:615)
  at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:434)
  at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:838)
  at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:480)
  at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
  at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
  at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
  at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
  at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
  at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)`

Unfortunately I am unable to reproduce it.

**Comment by MohammadMD1383** [comment]
well, I think this should be because of the contents of your clipboard,

I'll fix it
