### ISSUE TITLE
BUG: 3.16 macro error

### ISSUE THREAD

**Issue by j-a-s-o-n-g** [MohammadMD1383/Actionable#35]
Opened the new macro settings on a fresh install:

`java.lang.NullPointerException: Cannot invoke "String.isEmpty()" because "segment" is null
  at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:224)
  at java.base/java.nio.file.Path.of(Path.java:147)
  at java.base/java.nio.file.Paths.get(Paths.java:69)
  at ir.mmd.intellijDev.Actionable.text.macro.settings.UI$1.documentChanged(UI.java:63)
  at com.intellij.openapi.editor.impl.DocumentImpl.lambda$changedUpdate$2(DocumentImpl.java:922)
  at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeNonCancelableSection$3(CoreProgressManager.java:224)
  at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:664)
  at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:620)
  at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$computeInNonCancelableSection$4(CoreProgressManager.java:232)
  at com.intellij.openapi.progress.Cancellation.computeInNonCancelableSection(Cancellation.java:99)
  at com.intellij.openapi.progress.impl.CoreProgressManager.computeInNonCancelableSection(CoreProgressManager.java:232)
  at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:223)
  at com.intellij.openapi.editor.impl.DocumentImpl.changedUpdate(DocumentImpl.java:919)
  at com.intellij.openapi.editor.impl.DocumentImpl.updateText(DocumentImpl.java:823)
  at com.intellij.openapi.editor.impl.DocumentImpl.insertString(DocumentImpl.java:555)
  at com.intellij.openapi.editor.EditorModificationUtilEx.insertStringAtCaretNoScrolling(EditorModificationUtilEx.java:79)
  at com.intellij.openapi.editor.EditorModificationUtilEx.insertStringAtCaret(EditorModificationUtilEx.java:55)
  at com.intellij.openapi.editor.EditorModificationUtilEx.insertStringAtCaret(EditorModificationUtilEx.java:47)
  at com.intellij.openapi.editor.impl.EditorCopyPasteHelperImpl.insertStringAtCaret(EditorCopyPasteHelperImpl.java:213)
  at com.intellij.openapi.editor.impl.EditorCopyPasteHelperImpl.lambda$pasteTransferable$1(EditorCopyPasteHelperImpl.java:143)
  at com.intellij.openapi.editor.impl.CaretModelImpl.lambda$runForEachCaret$3(CaretModelImpl.java:310)
  at com.intellij.openapi.editor.impl.CaretModelImpl.doWithCaretMerging(CaretModelImpl.java:419)
  at com.intellij.openapi.editor.impl.CaretModelImpl.runForEachCaret(CaretModelImpl.java:319)
  at com.intellij.openapi.editor.impl.CaretModelImpl.runForEachCaret(CaretModelImpl.java:296)
  at com.intellij.openapi.editor.impl.EditorCopyPasteHelperImpl.pasteTransferable(EditorCopyPasteHelperImpl.java:141)
  at com.intellij.openapi.editor.actions.PasteAction$Handler.executeWriteAction(PasteAction.java:28)
  at com.intellij.openapi.editor.actionSystem.EditorWriteActionHandler$1.run(EditorWriteActionHandler.java:56)
  at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:955)
  at com.intellij.openapi.editor.actionSystem.EditorWriteActionHandler.doExecute(EditorWriteActionHandler.java:70)
  at com.intellij.openapi.editor.actions.BasePasteHandler.doExecute(BasePasteHandler.java:44)
  at com.intellij.openapi.editor.actionSystem.EditorActionHandler.lambda$execute$4(EditorActionHandler.java:199)
  at com.intellij.openapi.editor.actionSystem.EditorActionHandler.doIfEnabled(EditorActionHandler.java:89)
  at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:198)
  at com.intellij.codeInsight.editorActions.PasteHandler.execute(PasteHandler.java:86)
  at com.intellij.codeInsight.editorActions.PasteHandler.doExecute(PasteHandler.java:57)
  at com.intellij.openapi.editor.actionSystem.EditorActionHandler.lambda$execute$4(EditorActionHandler.java:199)
  at com.intellij.openapi.editor.actionSystem.EditorActionHandler.doIfEnabled(EditorActionHandler.java:89)
  at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:198)
  at com.intellij.codeInsight.editorActions.LanguageConsolePasteHandler.doExecute(LanguageConsolePasteHandler.kt:24)
  at com.intellij.openapi.editor.actionSystem.DynamicEditorActionHandler.doExecute(DynamicEditorActionHandler.java:63)
  at com.intellij.openapi.editor.actionSystem.EditorActionHandler.lambda$execute$4(EditorActionHandler.java:199)
  at com.intellij.openapi.editor.actionSystem.EditorActionHandler.doIfEnabled(EditorActionHandler.java:89)
  at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:198)
  at com.intellij.openapi.editor.actionSystem.EditorAction.lambda$actionPerformed$0(EditorAction.java:93)
  at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:219)
  at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:174)
  at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:102)
  at com.intellij.openapi.editor.impl.EditorImpl$MyEditable.executeAction(EditorImpl.java:3353)
  at com.intellij.openapi.editor.impl.EditorImpl$MyEditable.performPaste(EditorImpl.java:3326)
  at com.intellij.ide.actions.PasteAction.actionPerformed(PasteAction.java:35)
  at com.intellij.openapi.actionSystem.ex.ActionUtil.doPerformActionOrShowPopup(ActionUtil.java:323)
  at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performActionDumbAwareWithCallbacks$4(ActionUtil.java:302)
  at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:346)
  at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks(ActionUtil.java:302)
  at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$performAction$5(ActionMenuItem.java:296)
  at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:226)
  at com.intellij.openapi.actionSystem.impl.ActionMenuItem.performAction(ActionMenuItem.java:289)
  at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$new$0(ActionMenuItem.java:64)
  at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
  at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$4(ActionMenuItem.java:111)
  at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
  at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:94)
  at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:111)
  at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:526)
  at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:558)
  at java.desktop/java.awt.Component.processMouseEvent(Component.java:6648)
  at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3392)
  at java.desktop/java.awt.Component.processEvent(Component.java:6413)
  at java.desktop/java.awt.Container.processEvent(Container.java:2266)
  at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5022)
  at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
  at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
  at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
  at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
  at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
  at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
  at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2802)
  at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
  at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)
  at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
  at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
  at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
  at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
  at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
  at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:754)
  at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:752)
  at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
  at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
  at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:751)
  at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:909)
  at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:831)
  at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:753)
  at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$5(IdeEventQueue.java:437)
  at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:772)
  at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:436)
  at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
  at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:615)
  at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:434)
  at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:813)
  at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:480)
  at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
  at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
  at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:121)
  at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:191)
  at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:236)
  at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:234)
  at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
  at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:234)
  at java.desktop/java.awt.Dialog.show(Dialog.java:1080)
  at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:743)
  at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:467)
  at com.intellij.openapi.ui.DialogWrapper.doShow(DialogWrapper.java:1676)
  at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1634)
  at com.intellij.ide.actions.ShowSettingsUtilImpl.showSettingsDialog(ShowSettingsUtilImpl.java:90)
  at com.intellij.ide.actions.ShowSettingsAction.perform(ShowSettingsAction.java:60)
  at com.intellij.ide.actions.ShowSettingsAction.actionPerformed(ShowSettingsAction.java:47)
  at com.intellij.openapi.actionSystem.ex.ActionUtil.doPerformActionOrShowPopup(ActionUtil.java:323)
  at com.intellij.openapi.keymap.impl.ActionProcessor.performAction(ActionProcessor.java:47)
  at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:584)
  at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$doPerformActionInner$9(IdeKeyEventDispatcher.java:706)
  at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
  at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:94)
  at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$doPerformActionInner$10(IdeKeyEventDispatcher.java:706)
  at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:346)
  at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.doPerformActionInner(IdeKeyEventDispatcher.java:703)
  at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:647)
  at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:595)
  at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:478)
  at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:467)
  at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:225)
  at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.java:815)
  at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:750)
  at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$5(IdeEventQueue.java:437)
  at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:772)
  at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:436)
  at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
  at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:615)
  at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:434)
  at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:813)
  at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:480)
  at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
  at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
  at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
  at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
  at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
  at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
`

**Comment by MohammadMD1383** [comment]
Well this error was because of you were writing into an editor that wasn't associated with any item.

in this fix I made the editor invisible when there are no items available.

you have to make a file e.g. `my_macro.txt` in the path which is provided at the settings page which is `$IDE_CONFIG_PATH$/Actionable/macro/` and then you are able to edit that file in the ide too.
